FROM python:3.10-slim

WORKDIR /app

# Install Python dependencies
COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r ./requirements.txt

# Copy application code
COPY ./src ./src
COPY ./config ./config

# Expose the web interface port
EXPOSE 3055

CMD ["python", "./src/web_interface.py"]